### ISSUE TITLE
Errors on initial import

### ISSUE THREAD

**Issue by FerryInterface** [FizzCube/FizzySteamyMirror#1]
Installing FizzySteamyMirror with the current 2018 branch of Mirror does not work due to some classes and other things being altered.

"type or namespace 'TransportLayer' could not be found" error.

Can be fixed by adding
`using Mirror.Transport;`
at the top of the script.

Guide in the Readme to use FSM is also wrong -
instead of `Transport.layer = new FizzySteamyMirror();`
it should be
`NetworkManager.transport = new FizzySteamyMirror();`

**Comment by FerryInterface** [comment]
Fixed as of last few commits

**Comment by zukas3** [comment]
Which commit of Mirror did this package work with?
