### ISSUE TITLE
Namespace errors

### ISSUE THREAD

**Issue by mickev36** [FizzCube/FizzySteamyMirror#7]
Hi,

When installing the .cs files, i get those two error messages : 

Assets\Plugins\FizzySteamyMirror\FizzySteamyMirror.cs(4,7): error CS0138: A 'using namespace' directive can only be applied to namespaces; 'Transport' is a type not a namespace. Consider a 'using static' directive instead

Assets\Plugins\FizzySteamyMirror\FizzySteamyMirror.cs(6,34): error CS0246: The type or namespace name 'TransportLayer' could not be found (are you missing a using directive or an assembly reference?)

Any help would be appreciated ! Thanks in advance

**Comment by PixelFireXY** [comment]
For those who don't know how to solve this, is because the scripts are too old.
You have to import the package made by the community that forked the repo:
https://github.com/Chykary/FizzySteamworks

**Comment by mickev36** [comment]
Sorry, late to the party. Indeed, this repository doesn't seem to be maintained anymore, Chykary's fork is functionnal as PixelFireXY pointed out
